// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PreparedLogger.DataAccess.Sqlite;

namespace PreparedLogger.DataAccess.Sqlite.Migrations
{
    [DbContext(typeof(PreparedLoggerContext_Sqlite))]
    [Migration("20181007203635_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("PreparedLogger.Models.Log", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.HasKey("LogID");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("PreparedLogger.Models.LogEntry", b =>
                {
                    b.Property<int>("LogEntryID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LogID");

                    b.Property<string>("Message");

                    b.Property<DateTime>("Time");

                    b.HasKey("LogEntryID");

                    b.HasIndex("LogID");

                    b.ToTable("LogEntry");
                });

            modelBuilder.Entity("PreparedLogger.Models.LogEntry", b =>
                {
                    b.HasOne("PreparedLogger.Models.Log", "Log")
                        .WithMany("LogEntries")
                        .HasForeignKey("LogID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
